export const MODULES = {
    AUTH: {
        AUTH: 'auth',
        LOGIN: 'login',
        PERSONAL: 'personal',
        REGISTER: 'register',
        REGISTER_MOBILE: 'mobile',
        RECOVERY_PASSWORD: 'recoveryPassword',
        CHANGE_PASSWORD: 'changePassword'
    },
    USERS: {
        USERS: 'users',
        USERS_CCOMERCIALES: 'users_ccomerciales',
        PERFILES: 'perfiles',
        PERFILES_MODULOS: 'perfiles_modulos',
        USERS_INFORMACION: 'users_informacion'
    },
    MODULOS: 'modulos',
    LICENCIAS: 'licencias',
    PLANES: 'planes',
    CCOMERCIALES: 'ccomerciales',
    GALERIA: 'galeria',
    CATEGORIAS: 'categorias',
    TIENDAS: 'tiendas',
    PUBLICACIONES: 'publicaciones',
    GUARDADOS: 'guardados',
    COMENTARIOS: 'comentarios',
    LIKES: 'likes',
    PAISES: 'paises',
    CIUDADES: 'ciudades',
    TIPOS_PUBLICACION: 'tipos_publicacion',
    MENSAJES: 'mensajes',
    CONTACTOS: 'contactos',
    HORARIOS: 'horarios',
    PRODUCTOS: 'productos',
}