export const MODULES = {
    AUTH: {
        AUTH: 'auth',
        LOGIN: 'login',
        PERSONAL: 'personal',
        REGISTER: 'register',
        REGISTER_MOBILE: 'mobile',
        RECOVERY_PASSWORD: 'recoveryPassword',
        CHANGE_PASSWORD: 'changePassword'
    },
    UBIGEO: {
        UBIGEO: 'ubigeo',
        PAISES: 'paises',
        EDO: 'estados',
        MCPIO: 'municipios',
        PARR: 'parroquias',
        CIU: 'ciudades',
    },
    USERS: {
        USERS: 'users',
        USERS_CCOMERCIALES: 'users_ccomerciales',
        PERFILES: 'perfiles',
        PERFILES_MODULOS: 'perfiles_modulos',
        USERS_INFORMACION: 'users_informacion'
    },
    MODULOS: 'modulos',
    LICENCIAS: 'licencias',
    PLANES: 'planes',
    CCOMERCIALES: 'ccomerciales',
    CCOMERCIALES_GALERIA: 'ccomerciales_galeria',
    GALERIA: 'galeria',
    CATEGORIAS: 'categorias',
    TIENDAS: 'tiendas',
    TIENDAS_GALERIA: 'tiendas_galeria',
    PUBLICACIONES: 'publicaciones',
    PUBLICACIONES_GALERIA: 'publicaciones_galeria',
    GUARDADOS: 'guardados',
    COMENTARIOS: 'comentarios',
    LIKES: 'likes',
    CIUDADES: 'ciudades',
    TIPOS_PUBLICACION: 'tipos_publicacion',
    MENSAJES: 'mensajes',
    CONTACTOS: 'contactos',
    HORARIOS: 'horarios',
    PRODUCTOS: 'productos',
    PRODUCTOS_GALERIA: 'productos_galeria',
    CINES: {
        CINES: 'cines',
        CINES_GALERIA: 'cines_galeria',
        CINES_PELICULAS: 'cines_peliculas',
        CINES_CCOMERCIALES: 'cines_ccomerciales',
        PELICULAS: 'peliculas',
    },
}